### ISSUE TITLE
can I run kutt on MySQL

### ISSUE THREAD

**Issue by yujinqiu** [thedevs-network/kutt#294]
Hi, 
kutt seems good fit for me excepts the PostgreSQL database.  I've much more production expirence on MySQL. Is it possible to run on top of MySQL now ?

**Comment by poeti8** [comment]
Not by default. But since we're using Knex as the query build I'd say more than 90% of the queries should work fine, what you need to do is to find Postgres-only functions in the code and change them to something that MySQL supports. 

For example this `uuid` function is for Postgres only and you should find an alternative:
https://github.com/thedevs-network/kutt/blob/029b93d24a3a5044bde5ef0f8358f12550f5b1e4/server/models/link.ts#L46

**Comment by vlude** [comment]
I saw this issue and began examining which parts had to be changed. I found out that you are using knex.raw quite often. What is the advantage of using knex if you're making direct postgres statements with knex.raw? By using knex, it should have been quite easy to switch db

**Comment by vin-ni** [comment]
are there any news on this?

**Comment by poeti8** [comment]
@vin-ni yes, still not possible because of Postgress db functions which I have used.

**Comment by YouveGotMeowxy** [comment]
> @vin-ni yes, still not possible because of Postgress db functions which I have used.

Ahhh damn. Not gonna install it then. It would be the only container out of at least 70 that I'm running that use postgres. Not looking for all the overhead for 1 container. :/
