### ISSUE TITLE
Malware on website

### ISSUE THREAD

**Issue by kitesurf** [thedevs-network/kutt#340]
I had a malware advise by using the site:
(MALWARE_WBRS, -6.0, rproxy1.caib.es, 10.215.50.93, CAIB\u109347@ADCAIB, Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36, https://kutt.it/QWwaP5)

**Comment by FredyC** [comment]
It's even on WOT blacklist ... https://www.mywot.com/en/scorecard/kutt.it

**Comment by trgwii** [comment]
@kitesurf where did this malware advice come from? What does it look like? There is probably a service Kutt is listed on, we would need to contact them to get it removed.

**Comment by kitesurf** [comment]
@trgwii By using a link from the service on a computer from the Balearic Islands government ( rproxy1.caib.es )

**Comment by trgwii** [comment]
I'm not sure if we'll be able to fix this issue without knowing specifically what kind of blocklist / firewall software was used in this case so we can send them a message and get them to remove kutt.it.

**Comment by Bhupesh-V** [comment]
Speaking of malware, Twitter reports kutt links to be malware, you can't tweet them or even add them in bio :(

**Comment by MKRhere** [comment]
Unfortunately, too many blocklists are ready to jump the gun on one report of a misleading phishing or malware URL shortened with Kutt. We have a report system: https://kutt.it/report for them to contact us through and we regularly remove malware. We reach out to known blocklists to remove Kutt from them.

If you're affected by this, one bandaid solution might be to use custom domains. On the other hand, if you were sent a Kutt URL and are unable to visit it because of a firewall, we're likely unable to help except by appealing to the blocklist (do share the name of the blocklist and we'll try to reach out to them).

Closing this issue as it's not actionable, but feel free to comment if you have more to add and we could reopen.
