### ISSUE TITLE
How to run Custom Domain self-hosted?

### ISSUE THREAD

**Issue by kmanojkumar** [thedevs-network/kutt#341]
Hi,

My use-case is as follows:

1. I have self-hosted Kutt on https://kutt.abc.com
2. I want to use another domain for short urls i.e. https://xyz.in

Can you please share the configurations to be done for enabling custom domain https://xyz.in?

Also, to enable the HTTPS for https://xyz.in, there is an option to be set as true in the .env file. 
`CUSTOM_DOMAIN_USE_HTTPS=false`. What does this exactly do?

Lastly, how to add SSL certificates for this https://xyz.in, manually is also fine.

**Comment by NewRedsquare** [comment]
I'd like to know it yeah 👍

**Comment by arihantdaga** [comment]
I would like to know the same. 
Any help will be appreciated.

**Comment by poeti8** [comment]
You need to create an account, go to settings page and add that domain.
In order to add HTTPS, first set `CUSTOM_DOMAIN_USE_HTTPS=true` in Kutt, then add SSL certificates to NGNIX or whatever proxy server you are using.

By default Kutt uses HTTPS only for the default domain, `CUSTOM_DOMAIN_USE_HTTPS=true` makes it to use HTTPS for all domain.

**Comment by Saleh56** [comment]
في أحد، 29 نوفمبر، 2020 في 5:35 م، كتب Pouria Ezzati <
notifications@github.com>:

**Comment by arihantdaga** [comment]
Ok. Thank you very much @poeti8
