### ISSUE TITLE
How to configure default multi-domain

### ISSUE THREAD

**Issue by emperorjoker** [thedevs-network/kutt#376]
I mean, provide multi-domain options by admin for all registered users.

**Comment by poeti8** [comment]
I don't understand, please clarify.

**Comment by C129H223N3O54** [comment]
@poeti8 Hi, thanks for reply.
For example, setup default multi-domain _DEFAULT_DOMAIN="a.com,b.com,c.com,d.com"_  by admin in .env for global settings that all users can choose it from domain selection option.

**Comment by poeti8** [comment]
Ah I see, I can look into it in future.

**Comment by abett** [comment]
Would love this, too. then we could share links such as `example.com/abc` as well as `internal.example.com/abc`.  

Alternatively it'd be great to change the uniqueness constraint on `domains `from `address ` to `[address, user_id]` - then we can just make sure every user has the subdomains added as custom domains.  
However, I don't know whether that would crash any parts of the code, so I don't dare to touch this myself :)

**Comment by liukch** [comment]
We really need this, because custom domain just for only one user 
We use Kutt for the whole team, not for the public internet
So the default domain: a.example.com for the corp
the custom domain: b.example.com for the public

The web UI should be reached on a.example.com
And the shorter links should be reached on b.example.com
But every team member should login with his own account
I can not to this.
