### ISSUE TITLE
Custom Domain only working in single scenario, kutt.it link works in all

### ISSUE THREAD

**Issue by funzeye** [thedevs-network/kutt#386]
I have a link:
walshs.pub/drinks-menu

If it type that in as is it works fine,

However these do not:
www.walshs.pub/drinks-menu (404)
https://www.walshs.pub/drinks-menu (404)
https://walshs.pub/drinks-menu (Privacy Warning)

none of them work as I would expect

whereas this link to the same page - using kutt.it/JWl93O - works in all 4 above scenarios...

Anyone know reason for this??

I've added the A record for both www.walshs.pub and walshs.pub. Do I need to add something else in DNS or kutt settings?

Would like my custom link to work in all 4 scenarios as I cant be sure what user will enter before the short-link...

**Comment by arihantdaga** [comment]
@funzeye Did you figure out anything ? 
I am also facing the same problem, https not working
only http is working, and since firefox and microsoft edge are enforcing https, its not working at all for custom domains, it just throws the https error page. 

Can anyone comment on this, can custom domains work with https with kutt ?

**Comment by poeti8** [comment]
Now links starting with `www` should work as well. Domains that need HTTPS still need manual configuration by contacting support@kutt.it for now.
