### ISSUE TITLE
Kutt not running docker

### ISSUE THREAD

**Issue by techyporcupine** [thedevs-network/kutt#576]
Hello, so I am trying to setup Kutt on an Oracle Cloud Arm instance, and when I launch with `docker-compose up` I get the following
```
kutt_1      | #
kutt_1      | # Fatal process OOM in insufficient memory to create an Isolate
kutt_1      | #
```
Does anyone know why this is happening?

**Comment by l0u1sg** [comment]
I have the same problem on the same type of instance. Have you found a solution?

**Comment by techyporcupine** [comment]
Nope, sadly. It has something to do with the ARM processor. I just don't know what.

**Comment by santilococo** [comment]
The issue is related to the Alpine version used to build Kutt. To resolve this, you should build it using `alpine:3.14`.

You can use the following Docker image, which is built using `alpine:3.14` as the base image and is based on the latest available tag of Kutt: [slococo/kutt](https://hub.docker.com/r/slococo/kutt/tags).

Please don't hesitate to contact me if you encounter any issues while using it.

**Comment by techyporcupine** [comment]
Thank you for the answer! I don't currently have a machine to test it with, but I will close this issue because it seems that this might solve it!
